using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DevChallenges
{
    class FizzBuzz
    {
        static void Main(string[] args)
        {  
            // Enumerable.Range generates a sequence of numbers within a specific range, .Select specifies the values which will be projected by the sequence.
            Enumerable.Range(1, 100).Select( 
                              i =>
                              (i % 15 == 0) ? "FizzBuzz" :
                              (i % 3 == 0) ? "Fizz" : 
                              (i % 5 == 0) ? "Buzz" :
                              // Converts the integers of the sequence into a string.
                              i.ToString())
                             
                              // Creates a list from the sequence  of numbers generated by the enumerable object.
                              .ToList()  
                              
                              // Performs a specific action on each item within the list, for this application it will print each item within the list into the console.
                              .ForEach(Console.WriteLine); 

            Console.ReadLine();
        }
    }
}
